### ISSUE TITLE
Command line tools trick seems to have stopped working for Mavericks

### ISSUE THREAD

**Issue by phinze** [timsutton/osx-vm-templates#33]
Wonderful project - thank you!

The touch & softwareupdate trick doesn't seem to be working for the 10.9 VM I'm attempting to build.

```
==> vmware-iso: Provisioning with shell script: ../scripts/xcode-cli-tools.sh
    vmware-iso: Software Update Tool
    vmware-iso: Copyright 2002-2012 Apple Inc.
    vmware-iso:
    vmware-iso: Finding available software
    vmware-iso: : No such update
    vmware-iso: No updates are available.
```

This causes follow-up scripts to become rather sad, e.g.:

```
==> vmware-iso: Provisioning with shell script: ../scripts/puppet.sh
    vmware-iso: xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
    vmware-iso: /tmp/script.sh: line 54: /tmp/autopkg-Hc0Z/Code/autopkg: No such file or directory
    vmware-iso: /tmp/script.sh: line 41: /tmp/autopkg-Hc0Z/Code/autopkg: No such file or directory
    vmware-iso: Cannot parse a NULL or zero-length data
    vmware-iso: /tmp/script.sh: line 41: /tmp/autopkg-Hc0Z/Code/autopkg: No such file or directory
    vmware-iso: Cannot parse a NULL or zero-length data
    vmware-iso: /tmp/script.sh: line 41: /tmp/autopkg-Hc0Z/Code/autopkg: No such file or directory
    vmware-iso: Cannot parse a NULL or zero-length data
```

I'm looking into flipping back to the DMG-downloading strategy to see if that fixes things.

**Comment by timsutton** [comment]
Ouch. Took a quick glance, and Apple seems to not even be listing the CLI tools update currently in their Mavericks feed:

https://swscan.apple.com/content/catalogs/others/index-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog

The GUI to install CLI tools relies on this feed as well, so I wonder whether that works currently. When I can get some time to test further I will. Maybe the feed will be amended meantime, or we'll need to support some other method for adding the CLI tools (i.e. as downloaded from the dev portal).

**Comment by timsutton** [comment]
Yup, confirmed:

![screen shot 2015-04-27 at 8 38 26 pm](https://cloud.githubusercontent.com/assets/119358/7360826/829d7524-ed1d-11e4-834a-a5fc189a38c9.png)

**Comment by timsutton** [comment]
Filed bug report number [20720410](rdar://20720410)

**Comment by phinze** [comment]
Such sadness. I poked around the URL structure of the old public DMGs as well as the ADC downloads, but no luck. Cooking up a BYO-dmg option over here, will PR once I've vetted it.

**Comment by timsutton** [comment]
In the meantime, I realized I could get rid of the requirement of AutoPkg altogether for finding the latest Puppet tools versions, so failure of the CLI tools step should at least no longer make subsequent steps break: efe3938abef92f29517c156b59ef6b95be65cd84

I imagine you're a good person to ask (:smile:): If one wanted to be able to pass in some files to the build process using the file provisioner, for example, is there any way that this can be made optional according to a user var?

I know of some people who also include Xcode in their builds, for example, and I think they usually end up placing it on a private webserver that the build can fetch from within a provisioner step.

**Comment by timsutton** [comment]
As of about an hour ago, Apple put a 10.9 CLI tools back in their software update catalog. Haven't had a chance to test myself yet, though.

**Comment by phinze** [comment]
Sorry for going MIA on this - I had to put down my project for a bit. Glad to hear this got resolved upstream! I assume everything is working AOK now - I'll ping back if that's not the case. :+1:

**Comment by timsutton** [comment]
No worries! I'm glad they actually resolved the issue in a reasonable timeframe (for Apple).
