### ISSUE TITLE
dscl crashing

### ISSUE THREAD

**Issue by grahamgilbert** [timsutton/osx-vm-templates#37]
The command ``/usr/bin/dscl -plist . readall /Users`` results in a error of: 

```
dscl[999:76826] -[__NSCFNumber length]: unrecognized selector sent to instance 0xffffffc00000ff37
*** Uncaught Exception: <NSInvalidArgumentException> (-[__NSCFNumber length]: unrecognized selector sent to instance 0xffffffc00000ff37)
```

It seems to be caused by these two lines: https://github.com/timsutton/osx-vm-templates/blob/master/prepare_iso/support/pkg-postinstall#L40-L41

When they're commented out, the error disappears. I've never used ARD to access a Vagrant-built VM, so if there's no easy fix for what this does, I'd vote to remove it.

**Comment by timsutton** [comment]
Thanks! Missed this - it should be a string, not an int.
