### ISSUE TITLE
Specifying a disk size larger than 20 gb does not work!

### ISSUE THREAD

**Issue by dyundt** [timsutton/osx-vm-templates#41]
When I try to  create an osx Yosemite vagrant box (with following packer command): 

packer build \
 -var iso_url=../out/OSX_InstallESD_10.10.5_14F27.dmg \
 -var iso_checksum=xxxxxxxxxxxxxxxxxxxxxxxxxx \
 -var disk_size=40960 \
 -var username=vagrant \
 -var password=vagrant \
 -var autologin=true \
 -var install_vagrant_keys=true \
 -except vmware-iso,parallels-iso \
 template.json

The initial .vdi file is created with 40 gb of disk space, but when its exported to a vagrant box (and changed to a .vdmk file) the disk size is  changed to 20gb. When XCode requires 10+ gb of space alone this can be a problem. Has anyone found a workaround for this?

**Comment by timsutton** [comment]
Are you saying that the OS X guest actually sees the disk as only 20GB in size (when it was previously 40GB)?

**Comment by dyundt** [comment]
yes when the .vdi diskfile is exported to a .vdmk and compressed into a .box file the disk size changes from 40gb to 20gb. I was able to work around this by copying the .vdi before its deleted and creating a new vm from that, which I then created a base box from. I think the issue lies in the transition from a .vdi to a .vdmk.

**Comment by timsutton** [comment]
Looking more closely, I hadn't even realized that the vbox and parallels builders were set to 20GB.

`disk_size` isn't exposed as a user var, so I don't see how it would change the created disk to 40GB from the 20GB that's set in the template. You said that the initial vdi is created with 40GB... are you sure?

Aside from all this, I think a minimum of 40GB for all builders is perfectly sane and that we should probably be doing _at least_ that, if not more (for those who do set up large CI boxes with multiple Xcodes, etc.)

**Comment by dyundt** [comment]
Yes I modified the template. Sorry forgot to mention that. My template: 
{
  "builders": [
    {
      "boot_wait": "5s",
      "disk_size": 40960,
      "guest_os_type": "win-8",
      "iso_checksum_type": "md5",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_url": "{{user `iso_url`}}",
      "shutdown_command": "echo '{{user `username`}}'|sudo -S shutdown -h now",
      "ssh_port": 22,
      "ssh_username": "{{user `username`}}",
      "ssh_password": "{{user `password`}}",
      "ssh_wait_timeout": "10000s",
      "parallels_tools_flavor": "mac",
      "type": "parallels-iso",
      "prlctl": [
        ["set", "{{.Name}}", "--memsize", "2048"],
        ["set", "{{.Name}}", "--memquota", "512:2048"],
        ["set", "{{.Name}}", "--cpus", "2"],
        ["set", "{{.Name}}", "--distribution", "macosx"],
        ["set", "{{.Name}}", "--3d-accelerate", "highest"],
        ["set", "{{.Name}}", "--high-resolution", "off"],
        ["set", "{{.Name}}", "--auto-share-camera", "off"],
        ["set", "{{.Name}}", "--auto-share-bluetooth", "off"],
        ["set", "{{.Name}}", "--on-window-close", "keep-running"],
        ["set", "{{.Name}}", "--isolate-vm", "on"],
        ["set", "{{.Name}}", "--shf-host", "off"]
      ]
    },
    {
      "boot_wait": "2s",
      "disk_size": 40960,
      "guest_os_type": "darwin12-64",
      "iso_checksum_type": "md5",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_url": "{{user `iso_url`}}",
      "shutdown_command": "echo '{{user `username`}}'|sudo -S shutdown -h now",
      "skip_compaction": true,
      "ssh_port": 22,
      "ssh_username": "{{user `username`}}",
      "ssh_password": "{{user `password`}}",
      "ssh_wait_timeout": "10000s",
      "tools_upload_flavor": "darwin",
      "type": "vmware-iso",
      "vmx_data": {
        "cpuid.coresPerSocket": "1",
        "memsize": "4096",
        "numvcpus": "1",
        "firmware": "efi",
        "keyboardAndMouseProfile": "macProfile",
        "smc.present": "TRUE",
        "hpet0.present": "TRUE",
        "ich7m.present": "TRUE",
        "ehci.present": "TRUE",
        "usb.present": "TRUE"
      }
    },
    {
      "boot_wait": "2s",
      "disk_size": 40960,
      "guest_additions_mode": "disable",
      "guest_os_type": "MacOS1010_64",
      "hard_drive_interface": "sata",
      "iso_checksum_type": "md5",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_interface": "sata",
      "iso_url": "{{user `iso_url`}}",
      "shutdown_command": "echo '{{user `username`}}'|sudo -S shutdown -h now",
      "ssh_port": 22,
      "ssh_username": "{{user `username`}}",
      "ssh_password": "{{user `password`}}",
      "ssh_wait_timeout": "10000s",
      "type": "virtualbox-iso",
      "vboxmanage": [
        ["modifyvm", "{{.Name}}", "--audiocontroller", "hda"],
        ["modifyvm", "{{.Name}}", "--boot1", "dvd"],
        ["modifyvm", "{{.Name}}", "--boot2", "disk"],
        ["modifyvm", "{{.Name}}", "--chipset", "ich9"],
        ["modifyvm", "{{.Name}}", "--cpuidset", "00000001", "000306a9", "00020800", "80000201", "178bfbff"],
        ["modifyvm", "{{.Name}}", "--firmware", "efi"],
        ["modifyvm", "{{.Name}}", "--hpet", "on"],
        ["modifyvm", "{{.Name}}", "--keyboard", "usb"],
        ["modifyvm", "{{.Name}}", "--memory", "2048"],
        ["modifyvm", "{{.Name}}", "--mouse", "usbtablet"],
        ["modifyvm", "{{.Name}}", "--vram", "10"]
      ]
    }
  ],
  "min_packer_version": "0.7.0",
  "post-processors": [
    "vagrant"
  ],
  "provisioners": [
    {
      "destination": "/private/tmp/set_kcpassword.py",
      "source": "../scripts/support/set_kcpassword.py",
      "type": "file"
    },
    {
      "execute_command": "chmod +x {{ .Path }}; sudo {{ .Vars }} {{ .Path }}",
      "scripts": [
        "../scripts/vagrant.sh",
        "../scripts/xcode-cli-tools.sh",
        "../scripts/add-network-interface-detection.sh",
        "../scripts/autologin.sh",
        "../scripts/shrink.sh"
      ],
      "environment_vars": [
        "AUTOLOGIN={{user `autologin`}}",
        "CHEF_VERSION={{user `chef_version`}}",
        "FACTER_VERSION={{user `facter_version`}}",
        "HIERA_VERSION={{user `hiera_version`}}",
        "INSTALL_VAGRANT_KEYS={{user `install_vagrant_keys`}}",
        "PASSWORD={{user `password`}}",
        "PUPPET_VERSION={{user `puppet_version`}}",
        "UPDATE_SYSTEM={{user `update_system`}}",
        "USERNAME={{user `username`}}"
      ],
      "type": "shell"
    }
  ],
  "variables": {
    "autologin": "false",
    "chef_version": "latest",
    "facter_version": "latest",
    "hiera_version": "latest",
    "install_vagrant_keys": "true",
    "iso_checksum": "aff67f81dfbad7afda56c423473d61a6",
    "iso_url": "OSX_InstallESD_10.9.3_13D65.dmg",
    "password": "vagrant",
    "puppet_version": "latest",
    "update_system": "true",
    "username": "vagrant"
  }
}

**Comment by timsutton** [comment]
I just modified the templates to be all 40GB, and the resultant Vagrant boxes I see are now 40GB in size. Is this still not what you're seeing?

**Comment by dyundt** [comment]
Thanks for fixing it so quickly. I haven't run it since I reported the issue. Ill give it another try to verify. But Ill go ahead and close the issue.
