### ISSUE TITLE
User created by `prepare_ios.sh` is not in group 'staff'

### ISSUE THREAD

**Issue by cybertk** [timsutton/osx-vm-templates#51]
The creating user behaviour between `prepare_ios.sh` and `sysadminctl -addUser $user -admin` is different. 

The mainly issue here is user created by `prepare_ios.sh` is not a member of **staff**. 

Other observes

- **gid** created by `prepare_ios.sh` is **80**(admin) while `sysadminctl` is **20**(staff)

**Comment by timsutton** [comment]
You're right, and we should change this. I'm curious what issues you actually ran into as a result of this?

**Comment by timsutton** [comment]
Addressed here: https://github.com/timsutton/osx-vm-templates/commit/92f7cec57a9e643ae89f463952f2caef474624d4

Closing, but still curious what happened in your case, since the admin user is still at least part of the admin group.

**Comment by cybertk** [comment]
I want to share contents by group with a normal user.
