### ISSUE TITLE
Root partition often not created at boot

### ISSUE THREAD

**Issue by cournape** [timsutton/osx-vm-templates#54]
I am using those templates to create vagrant OS X boxes w/ vmware. It worked great for 10.7, but I see some issues w/ 10.9. In most cases (but not always), the install would stop early because the install cannot find a disk (see attachment).

The issue is not w/ my .dmg created through prepare_iso.sh, since installing that normally in vmware works w/o any issue. Also, if under packer, I go back in the install, manually create the partition, and continue the install works as expected (up to complete vagrant box build).

What is maddening is that it does not always fail :( Has anybody else encountered this ? Is there something I can do to debug this issue ?

I am using vmware 6.0.6 on Yosemite w/ packer 0.8.6

**Comment by cournape** [comment]
<img width="1136" alt="screen shot 2016-01-19 at 15 30 19" src="https://cloud.githubusercontent.com/assets/25111/12423052/975743ca-bec1-11e5-8c92-944157302c15.png">

**Comment by timsutton** [comment]
I _have_ seen some people loosen up the script in `rc.local` that assumes it will partition the first disk found, to at least also look for `disk1`. I think I saw it in at least a fork of this repo, and I'm also aware of another repo that did this. I'm not sure if that's the issue affecting you here, though.

When this happens it might be worth seeing the state of your drives with Disk Utility, and also taking note of the output of `diskutil list` in Terminal.

**Comment by cournape** [comment]
For future reference, re-creating the .dmg w/ the commit https://github.com/rodm/osx-vm-templates/commit/3eb8aa02a117756a10f723d6b1cc6c09aa3ede2a seems to fix it for me

**Comment by timsutton** [comment]
Thanks for confirming. I still find it weird that it's an intermittent problem, as though it's some kind of race condition. But I guess it's possible that since the OS X installer environment does need to mount other devices that they could get enumerated in a different order, and that the code in 10.9 happens to increase this likelihood.

**Comment by cournape** [comment]
Yes, it stumped me as well. I have never seen that issue w/ `10.7`, but could repeat it w/ `10.9` on different machines, w/ different versions of packer and/or Mac OS X host versions.

**Comment by phinze** [comment]
Hi friends,

I was getting a stalled installer reporting `Installing on (null)` so I came poking around the issues and found this.

Steps to reproduce my stall (on an 10.11 host w/ VMware Fusion 8.1.0):

```
sudo ./prepare_iso/prepare_iso.sh /Applications/Install\ OS\ X\ El\ Capitan.app out
packer build -var iso_checksum=5b309c620a3804dc4dc59d0751df301c -var iso_url=../out/OSX_InstallESD_10.11.3_15D21.dmg -only=vmware-iso template.json
```

Pulling the commit from https://github.com/timsutton/osx-vm-templates/issues/54#issuecomment-173262926 seems to have fixed it - I'm now watching an `Installing on "Macintosh HD"` progress bar do its thing. Thanks @cournape and @rodm!

@timsutton seem like worth making this change to the main repo?

**Comment by timsutton** [comment]
Thanks @phinze for sharing your results with 10.11! I wish it was easier to reproduce (I had no luck on 10.11), but since a few people have confirmed this as a workaround, LGTM. Thanks to @rodm and @cournape.
