### ISSUE TITLE
Sometimes xcode-cli-tools.sh hangs running softwareupdate

### ISSUE THREAD

**Issue by bacongravy** [timsutton/osx-vm-templates#59]
Very often when I run packer to build the template, the `xcode-cli-tools.sh` provisioning script hangs forever (well, at least for up to a few hours, before I give up and kill the build).

To debug this, I have logged in to the VM to investigate the running processes, and it appears that the `softwareupdate` tool is just sitting idle, and there is no evidence that the download ever started. If I kill the `softwareupdate` tool then provisioning continues.

I have noticed a similar issue with the `system-update.sh` step, if I get past the `xcode-cli-tools.sh` step.

I have attempted to work around this issue by adding a delay to the start of the `xcode-cli-tools.sh` script; a `sleep 30` seems to make the build work much more reliably for me.

I'm using OSX_InstallESD_10.11.3_15D21.dmg, packer 0.9.0, and VMware 8.1.0 with the [vmnet-natd patch](https://blogs.vmware.com/teamfusion/2016/01/workaround-of-nat-port-forwarding-issue-in-fusion-8-1.html).

**Comment by timsutton** [comment]
Merged in your sleep fix.. I also experienced networking stability issues with 8.1.0 to the point where I could no longer use it for certain things that would download from the internet, at least on my VMs that were using NAT. (Things like installing CocoaPods, or installers using cURL, would simply time out).

Reverting back to 8.0.2 fixed all those issues for me. Given the state of VMware Fusion I'm not sure exactly when we'll get another update, either...
