### ISSUE TITLE
Headless builds

### ISSUE THREAD

**Issue by chrmod** [timsutton/osx-vm-templates#68]
Does anyone know if headless builds are even possible? Tried it with vmware but they seem to hang on installation process. 
Didn't debug with VNC yet, but wanted to know if anyone tried it already.

**Comment by timsutton** [comment]
Last I tested they worked, but that was a while ago. I'd be surprised if that they didn't though, because AFAIK the guest doesn't really know it's "headless" - the hypervisor app is simply not rendering any console window. I'll see if I can do a test and confirm.

**Comment by chrmod** [comment]
alright, did the test again and it works perfectly well. Thanks

**Comment by timsutton** [comment]
Thank you for confirming!
