### ISSUE TITLE
Question -  the prepare iso script.

### ISSUE THREAD

**Issue by chrisRidgers** [timsutton/osx-vm-templates#70]
I'm attempting to use the prepare_iso script to modify generate an installer image that can be used to install OS X onto a physical mac computer.

I'm aware this isn't the original point of this repository, but the SSH access is ideal for setting up a machine which can be further modified with ansible over SSH.  Is there any advice you can offer, or reasons why this approach wouldn't work?

So far, I've managed to successfully generate the custom ISO, however booting from it on a Macbook Pro results in a 'no entry' symbol displayed on screen, while restoring the machines image from the generated image results in a boot process that takes hours to not finish, eventually logging a disk queue error.

Any advice much appreciated.

**Comment by clburlison** [comment]
@chrisRidgers You're correct this repo was not designed for what you're attempting to do. As such the output iso is not designed to be used for imaging physical Macs. 

What you should be looking at (it was designed for this task) is https://github.com/MagerValp/AutoDMG. It sounds like in total you're attempting to automate:
* creating a mac user account - use https://github.com/MagerValp/CreateUserPkg
* enabling ssh - Joe has an example here (specificly the configure_remote_access.sh) https://github.com/chilcote/vagrant-outset

**Comment by timsutton** [comment]
Thanks @clburlison - agreed on all counts.

**Comment by chrisRidgers** [comment]
Cheers for that.  I suspected I might end up looking elsewhere but this stuff looks great none the less.  Had to give it a go.  :P 

Cheers for the knowledge!
