### ISSUE TITLE
VirtualBox stuck after the restart

### ISSUE THREAD

**Issue by ffittschen** [timsutton/osx-vm-templates#72]
Hi,
I created the iso using the `prepare_iso.sh` script and then ran 

```
packer build \
    -var iso_url=OSX_InstallESD_10.11.6_15G31.dmg \
    -var autologin=true \
    -only virtualbox-iso \
    template.json
```

The box successfully started and installed OS X, but after the restart it got stuck at 

```
hfs: created HFBT on Macintosh HD
```

![screen shot 2016-08-23 at 17 04 47](https://cloud.githubusercontent.com/assets/7734806/17897907/2ec3c76c-6956-11e6-901d-cd88cfd57232.png)

`packer` then always times out waiting for the SSH connection.

Do you know what could cause this / how I can fix it to successfully build the vagrant box?

**Comment by xaocon** [comment]
I'm having the same problems. Has it ever worked for you before? This is my first attempt at using it so I'm not sure if it's a bug or something that I'm doing wrong.

**Comment by ffittschen** [comment]
@xaocon This is also my first attempt to use it. But after a few unsuccessful attempts, I tested the same setup with the trial version of VMWare (using `-only vmware-iso` instead of `-only virtualbox-iso`) and it worked like a charm on the very first try. But to use the created VMWare Vagrant box you also need the VMWare vagrant driver, which you have to buy additionally to VMWare... And I don't need VMWare for my use case. Virtualbox would do just fine...

**Comment by zigg** [comment]
@ffittschen @xaocon Have you checked the caveats for VirtualBox support? https://github.com/timsutton/osx-vm-templates#virtualbox-support

I haven't built a new box in some time, but I was able to successfully do it on 10.11.4.

**Comment by ffittschen** [comment]
@zigg Yes, I added the `-D DISABLE_REMOTE_MANAGEMENT` flag during iso preparation and I installed the VirtualBoy Extension Pack

**Comment by rickard-von-essen** [comment]
If you're thinking about buying VMware Fusion  compare it to Parallels
Desktop for Mac. The Vagrant provider for PD is free.

**Comment by timsutton** [comment]
Is this using VirtualBox 5.1.x? I can say that I _haven't_ tested any of the vbox support on that version, only 5.0.x.

**Comment by ffittschen** [comment]
@timsutton Yes I tried it with VirtualBox 5.1.4

**Comment by zigg** [comment]
I don't see myself having time to troubleshoot this one in the near future, so I would encourage whoever is interested in seeing it work in VirtualBox to try building out a DMG and seeing if a manual installation works (see https://gist.github.com/zigg/d6e0aa895b30106967f0 <https://gist.github.com/zigg/d6e0aa895b30106967f0> for a gist that I used to do this) and narrow down what might be failing that way.

Fair warning: it can be pretty time-consuming, and OS X fixes do not seem to be a high priority for VirtualBox (cf. https://www.virtualbox.org/ticket/14844 <https://www.virtualbox.org/ticket/14844>).

**Comment by xaocon** [comment]
Confirmed that mine works once downgraded to VirtualBox 5.0.26.

**Comment by timsutton** [comment]
Have a confirmation from someone running a Sierra guest with VBox 5.1.2, using these additional commands:

```
VBoxManage modifyvm "macOS Sierra" --cpuidset 00000001 000306a9 04100800 7fbae3ff bfebfbff
VBoxManage setextradata "macOS Sierra" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "MacBookPro11,3"
VBoxManage setextradata "macOS Sierra" "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0"
VBoxManage setextradata "macOS Sierra" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple"
VBoxManage setextradata "macOS Sierra" "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VBoxManage setextradata "macOS Sierra" "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
VBoxManage setextradata "macOS Sierra" VBoxInternal2/EfiGopMode 4```
```

Perhaps someone interested would like to test these out!

**Comment by zigg** [comment]
I'm hoping that entire configuration is not required.

**Comment by timsutton** [comment]
Me too. Just thought there may be something specific in terms of CPU
instructions like what we saw before.

**Comment by zigg** [comment]
I'm trying a few build variations in the background this afternoon.

**Comment by zigg** [comment]
Neither the complete set of tweaks above nor a few variations work. I'm staring at a box stuck after reboot in exactly the same place right now.

On top of that, on occasion the box didn't even reboot into its first post-install boot. 😞

**Comment by timsutton** [comment]
Looks like there's another project claiming to have a Mac guest working with 5.1.x: https://github.com/geerlingguy/macos-virtualbox-vm, which on first glance looks to be just setting `cpuidset`. Not using Packer though, perhaps there's some other difference I'm not seeing there.

**Comment by zigg** [comment]
I (or someone else) probably needs to spend a little time with a basic DMG install and see if anything we're doing is tripping a VirtualBox bug, like Remote Management has in the past.

**Comment by drodriguez** [comment]
I can confirm downgrading to 5.0.26 make the problem disappear (mine was stopping a little earlier than the screenshot, in the line "VM Swap Subsystem is ON”.

@zigg with the “manual installation” you mean creating the DMG with the gist you provided above and click through the graphical installation. I might be able to try that later (I want to try if the working box works when I upgrade VirtualBox after the creation, or I need to keep the version frozen).

**Comment by awgeorge** [comment]
f933ff55c37063a8685dc10350a995bee2b5ec7e - Fixes this issue.

**Comment by timsutton** [comment]
I also see someone else has implemented the same thing here: https://github.com/the-mx-group/osx-vm-templates/commit/e59a77f5b96309dcd170fccab658e5426fc55202

**Comment by zigg** [comment]
That's fine with me if people would like to go that way. It will mean VirtualBox VMs won't be able to support USB 2.0 devices, but that's probably not a particularly common use case.

Unfortunately, I don't have time to make that PR, so I'd encourage someone on this issue who has a good solution in hand to make that PR. Don't forget to update the documentation to note that we no longer need to install the extension pack.

**Comment by timsutton** [comment]
Reopening as a reminder to myself to update the Vbox docs for this.
