### ISSUE TITLE
suppress Sierra Siri prompt

### ISSUE THREAD

**Issue by viktorbenei** [timsutton/osx-vm-templates#76]
After a successful VM create and `vagrant up`, the user login is blocked by a Siri setup prompt.

<img width="1035" alt="screen shot 2016-11-20 at 1 06 11" src="https://cloud.githubusercontent.com/assets/430618/20459354/69a48f8a-aebe-11e6-88a4-0c245e6dd8b6.png">

This prevents the creation of some HOME/ folders, like `~/Desktop`.

Workaround: restarting the VM, e.g. with `vagrant halt && vagrant up`, the second boot skips the prompt.

**Comment by timsutton** [comment]
Thanks for raising this issue! I think this should address it, but let me know if it doesn't.

**Comment by viktorbenei** [comment]
Worked perfectly, thank you!

**Comment by timsutton** [comment]
🎉
